### PR TITLE
ci: unittests for helm chart

### PR DESCRIPTION
**Pull request by m-ildefons**
Add unit tests for helm chart.
The helm unittest plugin allows asserting the desired properties of the helm chart after templating. This can be leveraged to test complex templates and the creation/omission of resources depending on values provided in the values.yaml.
In addition to that, the chart testing program `ct` can be used to test various installation scenarios against a read K8s cluster.

- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.
- [x] CHANGELOG.md has been updated should there be relevant changes in this PR.

### CODE REVIEW

**Comment by giubacc** [comment]
This seems a very effective framework to test helm charts specific things.
Most likely, this approach, for the charts related testing, is preferable to the experimentation made within https://github.com/aquarist-labs/s3gw-acceptance.
I see this approach much more simple and concise in respect of using Go to test this.
I think `s3gw-acceptance` methodology is still valid for testing workflows with s3gw, but probably it is not worth to use that for charts, unless we have to do some specific complicated test not expressible with the tools used here.

Some clarifications needed:
It is not entirely clear to me how the configurations under `ci` are used by `ct`.

I've not understood this comment, what does it actually mean?
```
          # chart-testing is a little stupid in that if you don't explicitly
          # tell which charts you want tested, it will enforce that the charts
          # need to have changed. There is no other option to disable it.
```

**Comment by m-ildefons** [comment]
The comment relates to the default behavior of `ct` when no chart is specified (https://github.com/helm/chart-testing/blob/main/doc/ct_install.md).
When no chart is specified, it will assume that _all_ charts in the `charts` subdirectory should be tested. But it also assumes - and enforces - that at least one of those charts has received a version bump.
This is different from when you tell `ct` which charts to test, in which case a version bump is not enforced.
That means in order to pass testing without increasing the chart version over the last commit, a specific chart has to be specified to `ct`. It is IMO a little bit stupid to implicitly control the enforcement of such a test through specifying the chart. The comment should clarify why the chart is specified, because it's not obvious why the default behavior, auto discovery of charts, doesn't work in this case.

**Comment by m-ildefons** [comment]
This PR is ready for review. It doesn't cover everything that there is to cover, but I think it's more valuable to finally have the "unittest" infrastructure in place and be able to expand it than to wait until more test cases have been written.
The test cases within this PR can be expanded in following PRs easily.

**Comment by giubacc** [comment]
> The comment relates to the default behavior of `ct` when no chart is specified (https://github.com/helm/chart-testing/blob/main/doc/ct_install.md). When no chart is specified, it will assume that _all_ charts in the `charts` subdirectory should be tested. But it also assumes - and enforces - that at least one of those charts has received a version bump. This is different from when you tell `ct` which charts to test, in which case a version bump is not enforced. That means in order to pass testing without increasing the chart version over the last commit, a specific chart has to be specified to `ct`. It is IMO a little bit stupid to implicitly control the enforcement of such a test through specifying the chart. The comment should clarify why the chart is specified, because it's not obvious why the default behavior, auto discovery of charts, doesn't work in this case.

ok, suggestion: I'd only avoid to use the term stupid, I'd leave the explanation for the non obvious behavior keeping that judgment-neutral.

**Comment by m-ildefons** [comment]
Fair enough.

**Review by giubacc — APPROVED** [review]
lgtm

**Pull request merged**
