### PR TITLE
Add Rancher specific annotations

### PR DESCRIPTION
**Pull request by votdev**
- Set display name that is displayed in the App Marketplace instead of the chart name.

Bildschirmfoto vom 2023-09-05 10-20-54

- Set a fixed release name for the Helm installation. This can't be changed by the user.

Bildschirmfoto vom 2023-09-05 10-22-04

See https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/helm-charts-in-rancher/create-apps#chartyaml-annotations

Fixes: https://github.com/aquarist-labs/s3gw/issues/197

# Describe your changes

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] CHANGELOG.md has been updated should there be relevant changes in this PR.

### CODE REVIEW

**Comment by giubacc** [comment]
Concerned that, for the gateway, limit the user to install only one instance, could be actually unwanted/undesirable; consider that we can bind a single installation to exactly 1 pvc.
Forcing the release-name to be read-only means that the user can expose only 1 pvc with s3.
Ok, you can circumvent this by installing the gateway with a direct helm installation; but this behavior in the rancher window could mislead the user that 1 installation of the s3gw could actually manage more than 1 pvc; and this is not true.

**Comment by jecluis** [comment]
This sounds reasonable. We need to keep in mind that at this time the chart is still experimental, and we will likely not rely on it past LH 1.6.

Besides, even if the release name is read-only, the chart can be created on a different namespace. I think this behavior is sane.

@l-mb do you have an opinion on this?

**Comment by l-mb** [comment]
Agreed, I don't think we want anyone to install s3gw as a RM chart anymore, it'll rather be included as part of LH.

Guessing we might as well drop this instead.

**Comment by jecluis** [comment]
@l-mb in that case I think the right thing would be to wait for LH 1.6 to be out and then remove the chart from the rancher marketplace. Until then, having the chart behaving correctly seems appropriate.

**Comment by jecluis** [comment]
Regardless, I think given the above, it's reasonable to not further devote time and effort to enhancing the chart for the marketplace. Closing.

**Pull request closed without merging**
