### PR TITLE
Remove Traefik Dependency from chart

### PR DESCRIPTION
**Pull request by giubacc**
- Traefik dependency has been removed
- Traefik installation option has been removed

Fixes: https://github.com/aquarist-labs/s3gw-charts/issues/12
Signed-off-by: Giuseppe Baccini <giuseppe.baccini@suse.com>

### CODE REVIEW

**Review by jecluis — CHANGES_REQUESTED** [review]
I think somewhere in the README we should add Traefik as a dependency for the chart then.

Also, mind adding a `CHANGELOG` file to the repo with this change under a v0.1 section?

**Comment by giubacc** [comment]
> I think somewhere in the README we should add Traefik as a dependency for the chart then.
> 
> Also, mind adding a `CHANGELOG` file to the repo with this change under a v0.1 section?

Ok documenting this in the README.md. 
We can also add a CHANGELOG.md; but I'm more skeptic adding this change in the file.
We are basically releasing the first version, so we would add everything.
Let me know what do you think about this.
Also I have to mention that we are already versioning the helm chart at every commit; this is a rule in the CI that mandates that the version must increase.
We are currently at 0.1.6.

**Comment by giubacc** [comment]
A necessary clarification:
The sentence that at every commit the version must change is wrong.
The CI checks that the new version is different when upgrading:

```
------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 s3gw => (version: "0.1.6", path: "charts/s3gw")
------------------------------------------------------------------------------------------------------------------------
Linting chart 's3gw => (version: "0.1.6", path: "charts/s3gw")'
Checking chart 's3gw => (version: "0.1.6", path: "charts/s3gw")' for a version bump...
Old chart version: 0.1.5
New chart version: 0.1.6
Chart version ok.
Validating /home/runner/work/s3gw-charts/s3gw-charts/charts/s3gw/Chart.yaml...
Validation success! 👍
```

So this can be intended a check per PR and not per commit.

**Comment by jecluis** [comment]
> > I think somewhere in the README we should add Traefik as a dependency for the chart then.
> > Also, mind adding a `CHANGELOG` file to the repo with this change under a v0.1 section?
> 
> Ok documenting this in the README.md. We can also add a CHANGELOG.md; but I'm more skeptic adding this change in the file. We are basically releasing the first version, so we should add everything. Let me know what do you think about this. Also I have to mention that we are already versioning the helm chart at every commit; this is a rule in the CI that mandates that the version must increase. We are currently at 0.1.6.

I think it would make sense to have the version at the same level as the rest of the s3gw project. I understand it may not be feasible to change versions now, but in the future we should be releasing patch versions for the upcoming minor version.

For instance, a good way of having done this would be to have the chart version be a `0.0.x` up until we release version `0.1` of the project, and then the chart would be moved to `0.1.0` as well. From then on, it would be `0.1.x` up until version `0.2` was released, time when the chart would become `0.2.0`.

But assuming versions can't be changed, I'd say we keep increasing the patch version of the chart until we reach version `0.2.0` and then match the projects.

As for the CHANGELOG, maybe we can skip adding stuff to it for now, and start adding those changes after s3gw's `0.1.0` is released, and keep track of things for an upcoming `0.2.0 (unreleased)` version instead?

**Review by jecluis — CHANGES_REQUESTED** [review]

**Comment by giubacc** [comment]
> > > I think somewhere in the README we should add Traefik as a dependency for the chart then.
> > > Also, mind adding a `CHANGELOG` file to the repo with this change under a v0.1 section?
> > 
> > 
> > Ok documenting this in the README.md. We can also add a CHANGELOG.md; but I'm more skeptic adding this change in the file. We are basically releasing the first version, so we should add everything. Let me know what do you think about this. Also I have to mention that we are already versioning the helm chart at every commit; this is a rule in the CI that mandates that the version must increase. We are currently at 0.1.6.
> 
> I think it would make sense to have the version at the same level as the rest of the s3gw project. I understand it may not be feasible to change versions now, but in the future we should be releasing patch versions for the upcoming minor version.
> 
> For instance, a good way of having done this would be to have the chart version be a `0.0.x` up until we release version `0.1` of the project, and then the chart would be moved to `0.1.0` as well. From then on, it would be `0.1.x` up until version `0.2` was released, time when the chart would become `0.2.0`.
> 
> But assuming versions can't be changed, I'd say we keep increasing the patch version of the chart until we reach version `0.2.0` and then match the projects.
> 
> As for the CHANGELOG, maybe we can skip adding stuff to it for now, and start adding those changes after s3gw's `0.1.0` is released, and keep track of things for an upcoming `0.2.0 (unreleased)` version instead?

I like the idea of versioning the chart with `0.X.Y` where `X` is the main version of the project and `Y` is the maintenance number for the chart.

Because we are releasing the first version of s3gw we can still do whatever we want; so don't worry if now we are at `0.1.6`; we can easily change this to `0.1.0` tomorrow when we will release.
After that first release, though, we will have to adhere to the rule we agreed.

**Comment by jecluis** [comment]
> Because we are releasing the first version of s3gw we can still do whatever we want; so don't worry if now we are at `0.1.6`; we can easily change this to `0.1.0` tomorrow when we will release. After that first release, though, we will have to adhere to the rule we agreed.

sounds good to me :)

**Review by jecluis — APPROVED** [review]

**Pull request merged**
